[package]
name = "rust_spil"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
rand = "0.9.0"
serialport = "4.3"
bevy_egui = "0.24" # or the latest version compatible with your Bevy version
